export {default as About} from './About'
export {default as Footer} from './Footer/'
export {default as Headers} from './Headers/'
export {default as Skills} from './Skills/'
export {default as Works} from './Works/'
export {default as Navbar} from './Navbar/'
//export {default as Testimonial} from './testminoal/testminoal'